---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hpcc-deployment
    namespace: {{ .Values.namespace }}
    labels:
        app: hpcc

spec:
    replicas: {{ .Values.replicas}}

    selector:
        matchLabels:
            app: hpcc
    
    template:
        metadata:
            labels:
                app: hpcc

        spec:
            containers:
              - name: hpcc-app
                image: "{{ .Values.image}}:{{ .Values.image_version}}"
                ports:
                    - containerPort: {{ .Values.containerPort}}
                resources:
                    requests:
                        cpu: {{ .Values.requests_cpu }}
                        memory: {{ .Values.requests_memory }}
                    limits:
                        cpu: {{ .Values.limits_cpu }}
                        memory: {{ .Values.limits_memory }}